services:
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY:-xxx}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET:-xxx}
      STRIPE_PRICE_ID: ${STRIPE_PRICE_ID:-xxx}
      STRIPE_SUCCESS_URL: ${STRIPE_SUCCESS_URL:-http://localhost:3000/success}
      STRIPE_CANCEL_URL: ${STRIPE_CANCEL_URL:-http://localhost:3000/cancel}
      STRIPE_PORTAL_RETURN_URL: ${STRIPE_PORTAL_RETURN_URL:-http://localhost:3000/success}

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    profiles:
      - build

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  redisinsight:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"
    depends_on:
      - redis

volumes:
  redis_data:
